### ISSUE TITLE
Unsoundness in `MetroHash64::with_seed`

### ISSUE THREAD

**Issue by CraftSpider** [arthurprs/metrohash-rs#6]
Currently, `MetroHash64::with_seed` uses `mem::uninitialized`. This function is unsound in most situations, except if constructing  a type that is allowed to be entirely uninit (this is basically just `MaybeUninit` and types that consist entirely of `MaybeUninit` or padding).

To mitigate this, in practice, this function always returns a value filled with `0x01` bytes in non-miri or sanitizer environments, so calling it where it is is equivalent to writing `[0x0101010101010101; 4]`.

**Comment by arthurprs** [comment]
Thanks for the report. This library was written before these guidelines were created. Despite the warning, the exact usage was most likely safe.

Regardless, I took some time to modernize the library and release a new version 8a05133
